### ISSUE TITLE
Login with gitlab SSO 

### ISSUE THREAD

**Issue by ritesh** [mattermost/mattermost-bot-sample-golang#2]
Is it possible to login using gitlab single sign on? I'm using the GitLab omnibus edition that ships with mattermost. Users currently log in to mattermost via a "Sign in with gitlab" page which in turn uses LDAP.

**Comment by ralgozino** [comment]
Hello @ritesh 

I'm having exactly the same scenario as you. Have you been able to authenticate using GitLab SSO -> LDAP to mattermost?

**Comment by ritesh** [comment]
Sorry no, ended up writing my own bot that listens for HTTP requests from
mattermost.

**Comment by ralgozino** [comment]
I found a workaround here;
https://forum.mattermost.org/t/solved-how-to-authenticate-bots-using-the-api/2405/2

Thanks!

**Comment by ritesh** [comment]
Nice one! Thanks. Will give it a shot.

**Comment by jasonblais** [comment]
Hi @ritesh  and @ralgozino ,

Only the default GitLab SSO is officially supported. “Double SSO”, that is, chaining GitLab SSO to other SSO solutions like LDAP is not currently supported.

It may be possible to connect to use GitLab SSO in some cases with AD, LDAP, SAML, or MFA add-ons, but because of the special logic required they’re not officially supported and are known not to work on some instances.

If having official AD, LDAP, SAML or MFA support is critical to your enterprise, please consider purchasing [Mattermost Enterprise Edition](https://about.mattermost.com/pricing/).
